### ISSUE TITLE
Add oracle for safety calculation

### ISSUE THREAD

**Issue by naterush** [sigp/cbc-casper-js#1]
Currently, safety is [calculated for some estimate](https://github.com/sigp/cbc-casper-js/blob/master/validators/index.js#L98) by finding the proportion of validators whose latest messages have this estimate. 

However, because we insist on our protocols being safe without any timing assumptions, it's possible that there are some messages currently _floating about_ in the network that may change these validators minds. Thus, just checking the proportion of validators whose latest messages have the same estimate isn't enough (it's actually possible for all validators to have the same estimate on their latest messages [in some validator's view] but then they all end up switching because of messages floating around the network). 

Thus, to calculate safety for some estimate, we have to check a set of stronger conditions about recent messages from other validators using a safety oracle. The oracle that makes sense to implement is probably the Clique Oracle - which pretty much checks if validators are "locked in" to some specific message. 

You can see the python implementation of the clique oracle [here](https://github.com/ethereum/cbc-casper/blob/master/casper/safety_oracles/clique_oracle.py), and you can read it's specification [here](https://github.com/ethereum/research/blob/master/papers/CasperTFG/CasperTFG.tex#L380),  and you can hear it described [here](https://youtu.be/GNGbd_RbrzE?t=48m11s).

**Comment by paulhauner** [comment]
Ah yes, of course!

Thanks, will implement :)

**Comment by paulhauner** [comment]
I am working on a implementation, with reference to https://github.com/ethereum/cbc-casper/issues/178.

**Comment by paulhauner** [comment]
Allllrighty! I now have a binary safety oracle working as it should!

The code is a pretty messy, but I'll work to clean it up. It may be a bit easier for you to have a look once I've cleaned it up @naterush :)

Fully introduced in commit https://github.com/sigp/cbc-casper-js/commit/91e5304902a88793840cb1c776177c3d70cbfd92
